import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { db } from '../firebase';
import { doc, getDoc, updateDoc, addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { Loader2, ArrowLeft, Share2, ShoppingCart, CheckCircle } from 'lucide-react';
import { motion } from 'motion/react';
import { SEO } from '../components/SEO';
import { useAuth } from '../context/AuthContext';
import { useLanguage } from '../context/LanguageContext';
import { toast } from 'sonner';

export const PostView: React.FC = () => {
  const { cardId } = useParams<{ cardId: string }>();
  const { user } = useAuth();
  const { t } = useLanguage();
  const [card, setCard] = useState<any>(null);
  const [owner, setOwner] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [orderLoading, setOrderLoading] = useState(false);

  useEffect(() => {
    const fetchCard = async () => {
      if (!cardId) return;
      try {
        const docRef = doc(db, 'cards', cardId);
        const docSnap = await getDoc(docRef);
        if (docSnap.exists()) {
          const cardData = docSnap.data();
          setCard(cardData);
          
          // Fetch owner profile for username
          const ownerRef = doc(db, 'players', cardData.ownerId);
          const ownerSnap = await getDoc(ownerRef);
          if (ownerSnap.exists()) {
            setOwner(ownerSnap.data());
          }
        }
      } catch (error) {
        console.error("Error fetching card:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchCard();
  }, [cardId]);

  const handleOrderNow = async () => {
    if (!user || !card || card.status === 'ordered') return;
    setOrderLoading(true);
    try {
      await updateDoc(doc(db, 'cards', cardId!), {
        status: 'ordered'
      });

      await addDoc(collection(db, 'orders'), {
        cardId: cardId,
        userId: user.uid,
        userEmail: user.email,
        userName: user.displayName,
        characterName: card.characterName,
        imageUrl: card.imageUrl,
        status: 'pending',
        createdAt: serverTimestamp()
      });

      const adminEmails = ["selectedlegendbusiness@gmail.com", "fuadahmod174@gmail.com"];
      for (const email of adminEmails) {
        await addDoc(collection(db, 'notifications'), {
          userId: email,
          type: 'order',
          message: `New order from ${user.displayName} for ${card.characterName}`,
          read: false,
          createdAt: serverTimestamp(),
          link: `/card/${cardId}`
        });
      }

      setCard({ ...card, status: 'ordered' });
    } catch (err) {
      console.error("Order failed:", err);
    } finally {
      setOrderLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <Loader2 className="h-12 w-12 animate-spin text-emerald-500" />
      </div>
    );
  }

  if (!card) {
    return (
      <div className="flex min-h-[60vh] flex-col items-center justify-center gap-4 text-zinc-400">
        <p>{t('cardNotFound')}</p>
        <Link to="/" className="text-emerald-500 hover:underline">{t('returnHome')}</Link>
      </div>
    );
  }

  const shareUrl = window.location.href;
  const ownerName = card.ownerUsername 
    ? `@${card.ownerUsername}` 
    : (card.ownerDisplayName || owner?.username ? `@${owner.username}` : (owner?.displayName || "Unknown Collector"));
    
  const title = `${card.characterName} - Generated by ${ownerName} | FuadCards`;
  const description = `Anime: ${card.animeSource} | Power: ${card.raw_power} | Prompt: ${card.prompt_text} | Created by ${ownerName} on FuadCards.`;

  return (
    <div className="container mx-auto max-w-4xl px-4 py-12">
      <SEO 
        title={title} 
        description={description}
        image={card.imageUrl}
      />

      <Link to="/" className="mb-8 inline-flex items-center gap-2 text-zinc-400 hover:text-white">
        <ArrowLeft size={20} /> {t('back')}
      </Link>

      <div className="grid gap-12 md:grid-cols-2">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          className="relative aspect-[2.5/3.5] w-full max-w-[400px] mx-auto overflow-hidden rounded-xl shadow-2xl shadow-emerald-500/20"
        >
          <img 
            src={card.imageUrl} 
            alt={card.characterName} 
            className="h-full w-full object-cover" 
            referrerPolicy="no-referrer"
          />
        </motion.div>

          <div className="space-y-8">
            <div>
              <div className="flex items-center justify-between">
                <h1 className="text-4xl font-bold text-white">{card.characterName}</h1>
                {card.status === 'ordered' && (
                  <div className="flex items-center gap-2 rounded-full bg-amber-500 px-3 py-1 text-xs font-black text-black">
                    <CheckCircle size={14} /> {t('ordered')}
                  </div>
                )}
              </div>
              <p className="text-xl text-emerald-500">{card.animeSource}</p>
            </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
              <p className="text-sm text-zinc-400">{t('power')}</p>
              <p className="text-3xl font-bold text-white">{card.raw_power}</p>
            </div>
            <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
              <p className="text-sm text-zinc-400">{t('strength')}</p>
              <p className="text-3xl font-bold text-white">{card.strength}</p>
            </div>
          </div>

          <div className="rounded-xl border border-zinc-800 bg-zinc-900/50 p-6">
            <h3 className="mb-2 font-bold text-white">{t('loreReasoning')}</h3>
            <p className="text-zinc-400 italic">"{card.prompt_text}"</p>
          </div>

          <div className="flex flex-col gap-4">
            {user?.uid === card.ownerId && card.status !== 'ordered' && (
              <button
                onClick={handleOrderNow}
                disabled={orderLoading}
                className="flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-500 py-4 font-bold text-black hover:bg-emerald-400 disabled:opacity-50"
              >
                {orderLoading ? <Loader2 className="animate-spin" /> : <><ShoppingCart size={20} /> {t('orderPhysicalCard')}</>}
              </button>
            )}

            <button 
              onClick={() => {
                navigator.clipboard.writeText(shareUrl);
                toast.success(t('linkCopied'));
              }}
              className="flex w-full items-center justify-center gap-2 rounded-lg bg-zinc-800 py-4 font-bold text-white hover:bg-zinc-700"
            >
              <Share2 size={20} /> {t('shareCard')}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
